"""dev"""

CASES_TIME = 25
YOUNG_GUIDE_TIME = 180
ALREADY_TRY_JOB_TIME = YOUNG_GUIDE_TIME + 10
DONT_BUY_JOB_TIME = 60
CONFIRMATION_JOB_TIME = 20
SHOW_SHOP_TIME = 5 * 60

"""prod"""

# CASES_TIME = 15 * 60
# YOUNG_GUIDE_TIME = 10 * 60
# ALREADY_TRY_JOB_TIME = 15 * 60
# DONT_BUY_JOB_TIME = 60 * 60
# CONFIRMATION_JOB_TIME = 20
# SHOW_SHOP_TIME = 5 * 60
